RedHatInsights/widget-layout

- src/Components/Header/Header.scss
- src/Components/Header/Header.tsx
- src/Components/WidgetDrawer/WidgetDrawer.tsx
Jira: https://issues.redhat.com/browse/RHCLOUD-31189
Old
New
Old
New
> Header styling updates #1

- src/Components/Header/Header.scss
> Add bottom border to PageSections

- src/Components/WidgetDrawer/WidgetDrawer.tsx
> Add Widget card styling fix

- src/Components/Header/Header.tsx
> Move tooltip to the left

- src/Components/Header/Header.scss
- src/Components/Header/Header.tsx
> 'Dashboard Configuration' dropdown styling tweaks

- src/Components/DnDLayout/GridLayout.tsx
> Tweak breakpoints (3=> 4 columns)

- src/Components/DnDLayout/GridLayout.scss
> Tweak target styling

- src/Components/Header/Header.tsx
> Update mobile header styling

- src/Components/Header/Header.tsx
> Update tablet header styling

- src/Components/DnDLayout/GridTile.scss
- src/Components/DnDLayout/GridTile.tsx
- Remove ellipsis hack
-  Color icon
- Fix text wrapping without calculations
- put back` isDragging` code
Old
New
> Fix Card header styling

- src/Components/DnDLayout/GridTile.tsx
- src/Components/WidgetDrawer/WidgetDrawer.tsx
- src/Routes/Default/Default.tsx
Replaces: https://github.com/RedHatInsights/widget-layout/pull/14
Matches the mock and doesn't break the layout anymore- we can revisit later
Old
New
New
Mock
> dropdown fix

- src/Components/Widgets/widgetDefaults.ts
Set Large to 4 column and Medium to 2 column
> Update default width for large and medium widgets

- src/Components/DnDLayout/GridLayout.tsx
- src/Routes/Default/Default.tsx
> Sync widget and widget drawer padding

- src/App.scss
- src/Components/DnDLayout/GridTile.scss
- src/Components/DnDLayout/GridTile.tsx
- Moving styling back to this repo for the time being. 
- Tweak body class name
- Fix scrolling and flex issues
Old
New
> Styling fixes

- README.md
Add how to run chrome-services locally with widget layout
> Add readme section on how to run chrome-services locally with widget layout

- src/App.scss
Jira: https://issues.redhat.com/browse/RHCLOUD-31189
> Widget styling tweeks

- src/Components/Icons/images/ACSIcon.tsx
- src/Components/Icons/images/OpenShiftAIIcon.tsx
- src/Components/Icons/images/QuayIcon.tsx
> sync  icon sizes

- src/App.scss
> Adjust layout width and center

- src/Components/DnDLayout/GridLayout.tsx
Tweak row height. Depends on https://github.com/RedHatInsights/chrome-service-backend/pull/476
https://issues.redhat.com/browse/RHCLOUD-31643
---
---
##
##
> Tweak row height

- src/Components/DnDLayout/GridTile.tsx
Allow the Widget header link to drop to a second line when necessary.
[RHCLOUD-31871][(https://issues.redhat.com/browse/RHCLOUD-31871](https://issues.redhat.com/browse/RHCLOUD-31871))
---
---
##
##
> Header link fix

- src/Components/DnDLayout/GridLayout.tsx
- src/Components/Header/Header.tsx
- src/Routes/Default/Default.tsx
- src/api/dashboard-templates.ts
- src/hooks/useCurrentUser.ts
Chrome takes care of appending the auth header to http requests for us: https://github.com/RedHatInsights/insights-chrome/blob/master/src/utils/iqeEnablement.ts#L136
This PR falls back on that logic instead as our hook is not working. 
[RHCLOUD-31668](https://issues.redhat.com/browse/RHCLOUD-31668)
---
---
##
##
> RHCLOUD-31668: Remove broken JWT hook and rely on chrome to append auth header

- src/Components/WidgetDrawer/WidgetDrawer.tsx
Add 8px of additional spacing between the widget drawer descriptive text and the widgets
[RHCLOUD32231](https://issues.redhat.com/browse/RHCLOUD-32231)
---
---
##
##
> Tweak drawer padding

- src/Components/WidgetDrawer/WidgetDrawer.tsx
Fixes a regression caused by https://github.com/RedHatInsights/widget-layout/pull/71
[RHCLOUD-32327]([RHCLOUD-32327](https://issues.redhat.com/browse/RHCLOUD-32327))
---
---
##
##
> Fix Widget drawer styling

- src/App.scss
description text...
[RHCLOUD-31879](https://issues.redhat.com/browse/RHCLOUD-31879)
---
---
##
##
> Remove "Explore Capabilities" styling

- src/App.scss
description text...
[RHCLOUD-31879](https://issues.redhat.com/browse/RHCLOUD-31879)
---
---
##
##
> Remove 'simple service' and 'explore capabilities' widget styling

- src/App.scss
Relates to: https://github.com/RedHatInsights/notifications-frontend/pull/553
[RHCLOUD-31879](https://issues.redhat.com/browse/RHCLOUD-31879)
---
---
##
##
> Remove 'events' widget styling

- src/App.scss
Relates to: https://github.com/RedHatInsights/learning-resources/pull/47
[RHCLOUD-31879](https://issues.redhat.com/browse/RHCLOUD-31879)
---
---
##
##
> Remove 'learning resources' styling widget styling

- src/Components/DnDLayout/GridTile.scss
- src/Components/DnDLayout/GridTile.tsx
Add background to card header. Tweak action padding to prevent title wrapping. Adjust link text styling
---
---
##
##
> tweak header styling

- src/Components/DnDLayout/GridTile.scss
- src/Components/WidgetDrawer/WidgetDrawer.scss
- Shrink spacing between kebab and grabber
- Fix widget drawer card background color
- Delete unused styling
---
[RHCLOUD-32644](https://issues.redhat.com/browse/RHCLOUD-32644)
---
##
##
> drawer and widget header styling tweaks

- src/Components/Header/Header.tsx
Adding OUIA to add widget button for pendo
https://issues.redhat.com/browse/RHCLOUD-32802
---
No visible changes
---
##
##
> add OUIA to add widget button

- src/Components/DnDLayout/GridTile.tsx
Added unique ID to each widget element from default layout for testing purposes
[RHCLOUD-32148](https://issues.redhat.com/browse/RHCLOUD-32148)
---
##
##
> Added IDs to default layout widgets

- src/Components/DnDLayout/GridTile.tsx
Add more generic ouia IDs for each widget menu item. There can only be one menu active at one time so no need to target by the scope and widget type.
---
---
##
- [-] _(Optional) UX: Needs UX attention (end user UX modified, missing designs)_
- [-] _(Optional) UX: Has been mentioned_
##
> Add ouia IDs to widget menu

- src/Components/DnDLayout/GridTile.scss
Reduce card header padding to 16px
[RHCLOUD-32956](https://issues.redhat.com/browse/RHCLOUD-32956)
---
---
##
##
> tweak header padding

- src/Components/Header/Header.tsx
Adds an OUIA ID for the widget layout reset button so that test automation doesn't have to depend on button text.
---
---
##
##
> Add OUIA ID for widget layout reset button

- src/App.scss
Depends on: https://github.com/RedHatInsights/subscription-inventory-ui/pull/184
[RHCLOUD-32808](https://issues.redhat.com/browse/RHCLOUD-32808)
---
---
##
##
> Add widget body styling for subscriptions

- .tekton/widget-layout-pull-request.yaml
- .tekton/widget-layout-push.yaml
- Create test PR to trigger Konflux (step 5 [here](https://inscope.corp.redhat.com/docs/default/Component/consoledot-pages/containerized-frontends/konflux-frontends/))
- Set ref for frontend-build in the tekton yaml files.
[RHCLOUD-32459](https://issues.redhat.com/browse/RHCLOUD-32459)
---
---
##
##
> set ref for konflux frontend-build

- .tekton/widget-layout-pull-request.yaml
- README.md
description text...
[RHCLOUDXXXX](https://issues.redhat.com/browse/RHCLOUDXXXX)
---
---
##
##
> Trigger new konflux release

- src/Components/DnDLayout/GridLayout.tsx
- Uncomment link within empty state component to [added documentation](https://access.redhat.com/documentation/en-us/red_hat_hybrid_cloud_console/1-latest/html-single/getting_started_with_the_red_hat_hybrid_cloud_console/index#customizing-main-page_navigating-the-console). 
[RHCLOUD-31806](https://issues.redhat.com/browse/RHCLOUD-31806)
---
---
##
##
> add link to documentation to empty state component

- src/App.scss
Follow-up to: https://github.com/RedHatInsights/learning-resources/pull/72
[RHCLOUD-33756](https://issues.redhat.com/browse/RHCLOUD-33756)
---
---
##
##
> Add flex to Learning resources widget body

- src/Components/DnDLayout/GridLayout.tsx
- src/Components/DnDLayout/GridTile.tsx
Pendo analytics tracking for widgets move, add and remove. Uses the `analytics` functions provided by `useChrome()`. Uses the `widgetType` as the identifier for the Pendo events.
[RHCLOUD-34875](https://issues.redhat.com/browse/RHCLOUD-34875)
---
NA
NA
---
##
##
> [RHCLOUD-34875] Pendo add widgets tracking

- package-lock.json
- package.json
There is action required from our team to update @redhat-cloud-services/frontend-components-config to latest version
##
- [-] _(Optional) QE: Needs QE attention (OUIA changed, perceived impact to tests, no test coverage)_
- [-] _(Optional) QE: Has been mentioned_
- [-] _(Optional) UX: Needs UX attention (end user UX modified, missing designs)_
- [-] _(Optional) UX: Has been mentioned_
##
> Update config of frontend components

- .tekton/widget-layout-pull-request.yaml
- .tekton/widget-layout-push.yaml
We want to run unit tests as part of Konflux build pipeline
---
##
- [-] _(Optional) QE: Needs QE attention (OUIA changed, perceived impact to tests, no test coverage)_
- [-] _(Optional) QE: Has been mentioned_
- [-] _(Optional) UX: Needs UX attention (end user UX modified, missing designs)_
- [-] _(Optional) UX: Has been mentioned_
##
> Add unit test task to Konflux config

- src/Components/DnDLayout/GridLayout.tsx
description text...
Simple doc link update
[[RHCLOUD-33597](https://issues.redhat.com/browse/RHCLOUD-33597)
---
---
##
##
> Doc link update

- .github/CODEOWNERS
Let's add @RedHatInsights/platform-experience team as codeowners so we receive notifications when new PR is opened.
> ci(git): add codeowners

- src/Components/WidgetDrawer/WidgetDrawer.tsx
This is simply to add a unique OUIA ID to the "Add widget" cards on the widgetized landing page.
This will help with the testing effort.
CURRENTLY still in draft, simply copied over the titling method from the card itself. Assuming this works but haven't tested locally yet
[RHCLOUD37291](https://issues.redhat.com/browse/RHCLOUD37291)
---
---
##
##
> Added OUIA ID for add widget cards

- .gitmodules
- .tekton/widget-layout-pull-request.yaml
- .tekton/widget-layout-push.yaml
For [RHCLOUD-37969](https://issues.redhat.com/browse/RHCLOUD-37969)
> Update to use new build-tools

- src/Components/DnDLayout/GridLayout.scss
- src/Components/DnDLayout/GridTile.tsx
- tweak target corner radius and drag-icon positioning
[RHCLOUD-39409](https://issues.redhat.com/browse/RHCLOUD-39409)
---
---
##
##
> Tweak target and drag icon styling

- .tekton/widget-layout-pull-request.yaml
- .tekton/widget-layout-push.yaml
Add service accountName to avoid breakages once konflux migrates off of app studio one.
> fix(kofnlux): add service account to taskRunTemplate

- src/Components/DnDLayout/GridTile.tsx
Delete the second 'remove' icon
[RHCLOUD-40253](https://issues.redhat.com/browse/RHCLOUD-40253)
---
---
##
##
> Remove redundant icon from widget dropdown menu

- README.md
- docs/ai-agent-guidelines.md
- docs/components/custom-widgets.md
- docs/components/grid-layout.md
- docs/components/widget-layout.md
- docs/layout-data-format.md
No doce changes, only adding docs for existing stuff
> chore: add layout docs

- .tekton/widget-layout-sc-pull-request.yaml
- .tekton/widget-layout-sc-push.yaml
* Red Hat Konflux update widget-layout-sc
* shared pipelines revision
---------
Bringing the security-compliance tekton files to main.
> Red Hat Konflux update widget-layout-sc (#176)
